services:
  app:
    build: ./backend/theater-booking-system/
    container_name: theater-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - theater-net

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: theater
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5433"
    networks:
      - theater-net
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  theater-net:

