name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files to EC2
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: "/home/ec2-user/app"

    - name: SSH and deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ec2-user/app
          echo "DB_URL=${{ secrets.DB_URL }}" > .env.aws
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env.aws
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.aws
          echo "SPRING_PROFILES_ACTIVE=prod" >> .env.aws
          docker compose down
          docker compose -f docker-compose.aws.yml --env-file .env.aws up -d --build
